services:
  - type: web
    name: tg-random-bot
    runtime: docker
    plan: starter
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        value: "8039764773:AAHRs8IXhxaVFhFke2-QlDaryKAyvggKo34"
      - key: EXEED_CHANNEL_ID
        value: "@exeedrussia"
      - key: LUZHNIKI_CHANNEL_ID
        value: "@luzhniki_life"
      - key: EXEED_CHANNEL_URL
        value: "https://t.me/exeedrussia"
      - key: LUZHNIKI_CHANNEL_URL
        value: "https://t.me/luzhniki_life"
      - key: DAILY_SMALL_PRIZES
        value: "100"
      - key: DAILY_BIG_PRIZES
        value: "5"
      - key: DAILY_VISITORS
        value: "500"
      - key: SMALL_PRIZE_LIST
        value: "Брелок EXEED,Значок,Стикерпак,Ручка,Магнит"
      - key: BIG_PRIZE_LIST
        value: "Термокружка,Шарф,Шапка,Перчатки,Плед"
      - key: STORAGE_CHANNEL_ID
        value: "-1003612887645"
      - key: DATABASE_PATH
        value: "/data/database.db"
      - key: PHOTOS_DIR
        value: "/data/photos"
