services:
  - type: worker
    name: tg-random-bot
    runtime: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "8039764773:AAHRs8IXhxaVFhFke2-QlDaryKAyvggKo34"
      - key: EXEED_CHANNEL_ID
        value: "@exeed_russia"
      - key: LUZHNIKI_CHANNEL_ID
        value: "@luzhniki"
      - key: EXEED_CHANNEL_URL
        value: "https://t.me/exeed_russia"
      - key: LUZHNIKI_CHANNEL_URL
        value: "https://t.me/luzhniki"
      - key: DAILY_SMALL_PRIZES
        value: "100"
      - key: DAILY_BIG_PRIZES
        value: "5"
      - key: DAILY_VISITORS
        value: "6000"
      - key: SMALL_PRIZE_LIST
        value: "Брелок EXEED,Значок,Стикерпак,Ручка,Магнит"
      - key: BIG_PRIZE_LIST
        value: "Термокружка,Шарф,Шапка,Перчатки,Плед"
      - key: STORAGE_CHANNEL_ID
        value: "" # PLACEHOLDER: Enter Channel ID here (e.g., -100123456789)
